name: Publish Snapshot

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest

    # mark snapshot
    env:
      SNAPSHOT: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew assembleRelease

        # Generates other artifacts (javadocJar is optional)
      - name: Source jar and dokka
        run: ./gradlew sourcesJar javadocJar

        # Runs upload
      - name: Publish to MavenCentral Snapshot
        run: ./gradlew publishReleasePublicationToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

        # Runs upload
      - name: Publish to Github Packages Repository
        run: ./gradlew publishReleasePublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}